#!/usr/bin/env node
/**
 * Session Activity MCP Server
 *
 * Read-only access to session activity summaries generated by the
 * session-activity-broadcaster daemon. Agents use these tools to review
 * detailed per-session summaries and project-wide super-summaries.
 *
 * Database: .claude/state/session-activity.db (SQLite, WAL mode, read-only)
 * Tier: 2 (stateful, per-session stdio)
 *
 * @version 1.0.0
 */

import fs from 'fs';
import path from 'path';
import Database from 'better-sqlite3';
import { McpServer, type AnyToolHandler } from '../shared/server.js';
import {
  GetSessionSummaryArgsSchema,
  ListSessionSummariesArgsSchema,
  ListProjectSummariesArgsSchema,
  GetProjectSummaryArgsSchema,
  type GetSessionSummaryArgs,
  type ListSessionSummariesArgs,
  type ListProjectSummariesArgs,
  type GetProjectSummaryArgs,
  type SessionSummaryRecord,
  type ProjectSummaryRecord,
  type ErrorResult,
} from './types.js';

// ============================================================================
// Configuration
// ============================================================================

const PROJECT_DIR = path.resolve(process.env.CLAUDE_PROJECT_DIR || process.cwd());
const DB_PATH = path.join(PROJECT_DIR, '.claude', 'state', 'session-activity.db');

// ============================================================================
// Database (read-only — daemon owns writes)
// ============================================================================

let _db: Database.Database | null = null;

function getDb(): Database.Database {
  if (!_db) {
    if (!fs.existsSync(DB_PATH)) {
      throw new Error('session-activity.db not found. The session-activity-broadcaster daemon may not be running yet.');
    }
    _db = new Database(DB_PATH, { readonly: true });
    _db.pragma('journal_mode = WAL');
  }
  return _db;
}

function closeDb(): void {
  if (_db) { _db.close(); _db = null; }
}

// ============================================================================
// Tool Handlers
// ============================================================================

function getSessionSummary(args: GetSessionSummaryArgs): SessionSummaryRecord | ErrorResult {
  const db = getDb();
  const row = db.prepare('SELECT * FROM session_summaries WHERE id = ?').get(args.id) as SessionSummaryRecord | undefined;
  if (!row) return { error: `Session summary not found: ${args.id}` };
  return row;
}

function listSessionSummaries(args: ListSessionSummariesArgs): { summaries: Array<{ id: string; session_id: string | null; agent_id: string | null; title: string | null; preview: string; created_at: string }> } | ErrorResult {
  const db = getDb();
  const rows = db.prepare(
    `SELECT id, session_id, agent_id, title, substr(summary, 1, 120) AS preview, created_at
     FROM session_summaries
     WHERE session_id = ? OR agent_id = ?
     ORDER BY created_at DESC
     LIMIT ?`
  ).all(args.session_id, args.session_id, args.limit);
  return { summaries: rows as Array<{ id: string; session_id: string | null; agent_id: string | null; title: string | null; preview: string; created_at: string }> };
}

function listProjectSummaries(args: ListProjectSummariesArgs): { summaries: Array<{ id: string; session_count: number; preview: string; created_at: string }> } | ErrorResult {
  const db = getDb();
  const rows = db.prepare(
    `SELECT id, session_count, substr(summary, 1, 120) AS preview, created_at
     FROM project_summaries
     ORDER BY created_at DESC
     LIMIT ?`
  ).all(args.limit);
  return { summaries: rows as Array<{ id: string; session_count: number; preview: string; created_at: string }> };
}

function getProjectSummary(args: GetProjectSummaryArgs): ProjectSummaryRecord | ErrorResult {
  const db = getDb();
  const row = db.prepare('SELECT * FROM project_summaries WHERE id = ?').get(args.id) as ProjectSummaryRecord | undefined;
  if (!row) return { error: `Project summary not found: ${args.id}` };
  return row;
}

// ============================================================================
// Tool Registration
// ============================================================================

const tools: AnyToolHandler[] = [
  {
    name: 'get_session_summary',
    description: 'Get a detailed session activity summary by UUID. UUIDs are included in broadcast messages and returned by list_session_summaries.',
    schema: GetSessionSummaryArgsSchema,
    handler: getSessionSummary,
  },
  {
    name: 'list_session_summaries',
    description: 'List activity summaries for a specific session or agent. Returns UUID, timestamp, and 120-char preview for each. Use get_session_summary with UUID for full details.',
    schema: ListSessionSummariesArgsSchema,
    handler: listSessionSummaries,
  },
  {
    name: 'list_project_summaries',
    description: 'List project-wide super-summaries (unified digests of all session activity). Returns UUID, session count, timestamp, and preview.',
    schema: ListProjectSummariesArgsSchema,
    handler: listProjectSummaries,
  },
  {
    name: 'get_project_summary',
    description: 'Get a project-wide super-summary by UUID. These are unified digests covering all active sessions at a point in time.',
    schema: GetProjectSummaryArgsSchema,
    handler: getProjectSummary,
  },
];

// ============================================================================
// Server Lifecycle
// ============================================================================

// Conditional start: skip stdio when running inside the shared MCP daemon
if (!process.env.MCP_SHARED_DAEMON) {
  const server = new McpServer({
    name: 'session-activity',
    version: '1.0.0',
    tools,
  });

  process.on('SIGINT', () => { closeDb(); process.exit(0); });
  process.on('SIGTERM', () => { closeDb(); process.exit(0); });

  server.start();
}
